### ISSUE TITLE
Better than AFNetworking?

### ISSUE THREAD

**Issue by li6185377** [twitter/ios-twitter-network-layer#2]

**Comment by NSProgrammer** [comment]
I recommend reading the TNL blog post and README.md to learn more about the feature set TNL offers and comparing that with alternative networking frameworks.

https://blog.twitter.com/engineering/en_us/topics/open-source/2018/opensourcetnl.html

https://github.com/twitter/ios-twitter-network-layer/blob/master/README.md

We considered all networking options at Twitter before building TNL, nothing else met (nor meets) our needs.  FB’s internal network layer is the most viable choice but not open source.

I hope this indirect answer suffices.
