### ISSUE TITLE
Is there the plan to support CocoaPods?

### ISSUE THREAD

**Issue by brownsoo** [twitter/ios-twitter-network-layer#8]
When this appear in CocoaPods, if plan exists.

**Comment by NSProgrammer** [comment]
As with the other open source projects from Twitter, we don't use CocoaPods and so we don't build it into the initial release of our projects.  However, it is open source, and we are supportive of community members providing Pull Requests for CocoaPods or anything else that would benefit the repo.

Leaving this issue open for anyone in the community to volunteer to fix.

**Comment by brownsoo** [comment]
Thanks for your reply. I hope to be one providing P.R for CocoaPods, if I could.
